### ISSUE TITLE
Log file says FileNotFoundException deadstacks.dat

### ISSUE THREAD

**Issue by Lothrazar** [The-Fireplace/Nether-Essence#1]
[00:06:53] [Server thread/INFO]: [STDERR]: java.io.FileNotFoundException: C:\Users\Sam\Documents\Curse\Minecraft\Instances\OPNC2.0\saves\New Worldwf\deadstacks.dat (The system cannot find the path specified)
[00:06:53] [Server thread/INFO]: [STDERR]: 	at java.io.FileOutputStream.open(Native Method)
[00:06:53] [Server thread/INFO]: [STDERR]: 	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
[00:06:53] [Server thread/INFO]: [STDERR]: 	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
[00:06:53] [Server thread/INFO]: [STDERR]: 	at the_fireplace.netheressence.handlers.DeadStackData$.saveToFile(DeadStackData.scala:54)
[00:06:53] [Server thread/INFO]: [STDERR]: 	at the_fireplace.netheressence.handlers.DeadStackData$.save(DeadStackData.scala:22)
[00:06:53] [Server thread/INFO]: [STDERR]: 	at the_fireplace.netheressence.handlers.ForgeEvents.worldSave(ForgeEvents.scala:20)
[00:06:53] [Server thread/INFO]: [STDERR]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_239_ForgeEvents_worldSave_Unload.invoke(.dynamic)
[00:06:53] [Server thread/INFO]: [STDERR]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
[00:06:53] [Server thread/INFO]: [STDERR]: 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
[00:06:53] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:410)
[00:06:53] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.integrated.IntegratedServer.func_71260_j(IntegratedServer.java:328)
[00:06:53] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:535)
[00:06:53] [Server thread/INFO]: [STDERR]: 	at java.lang.Thread.run(Thread.java:745)

**Comment by The-Fireplace** [comment]
Alright, I'll fix it asap.

**Comment by The-Fireplace** [comment]
Fixed in 7.1.1
